[build]
  publish = "./"
  command = "echo 'build step'"

[[plugins]]
  package = "netlify-plugin-sitemap"

  [plugins.inputs]
  baseUrl = "https://trackvibe.netlify.app"
  sitemapPath = "sitemap.xml"
  generateRobotsTxt = true
  prettyURLs = false
